README.md
=> Adding Goals/Tasks

.gitignore, README.md, backend/Process.md, backend/package-lock.json, backend/package.json
=> Initial project setup (Incomple)

backend/app.js, backend/controllers/JobsTypeController.js, backend/controllers/authController.js, backend/models/JobTypeModel.js, backend/models/jobModel.js, backend/routes/jobsTypeRoutes.js, frontend/src/pages/NotFound.jsx
Not sure if any user or only admin should be able to create job ? Any views @vwakesahu ??
=>  Added a backend Feature user can create Job 

backend/controllers/JobsTypeController.js, backend/models/JobTypeModel.js, backend/routes/jobsTypeRoutes.js
Can Get All Job Types from DB to showcase it on home page
=> All Jobs List Access

backend/apiHelp.js, backend/app.js, backend/controllers/JobsTypeController.js, backend/controllers/jobsController.js, backend/models/JobTypeModel.js, backend/models/jobModel.js, backend/routes/jobRoutes.js
Now You can create job 
can view all jobs 
Created a file of formatted json for api request and also contains api list
=> Create Job API + Get All Jobs Api + api Help added [Backend Stuff]

frontend/src/components/HeroSection.jsx
=> Sucessfully Added SearchBar in Hero Section

frontend/src/App.jsx, frontend/src/components/NavBar.jsx, frontend/src/pages/Home.jsx, frontend/src/redux/store.js
Removed Navbar and Footer from Home.jsx and added it to App.jsx. cause of routing is in App.jsx so basically Navbar and Footer will constant trhought the Webapp and the middle components will be changed According to routes."/"
Reloacated Resource Page to resource tab.
Changed some li to Link tag for routing to particular "/" component.
Added Redux Store (Prop Drilling is not cool) will define states globally and use them throught the project on global context.
=> Front End Chnages

frontend/public/index.html
Title and icon changed @DevSwayam 😁
=> Change title/icon

frontend/public/index.html
Reverts TechieeGeeeks/JobSet#48 |
You need to push tje filer you using at as refference git add <%PUBLIC_URL%/static/media/shirt-svgrepo-com.svg>
=> Revert "Change title/icon"

frontend/src/components/SubcribeComponent.jsx
Closes #63 
**Updated the box-shadow of the Subscribe to newsletter Component.**
_Screenshot :_
=> Update box-shadow in SubcribeComponent.jsx

frontend/src/components/HomeCards.jsx, frontend/src/components/NavBar.jsx, frontend/src/components/SearchInput.jsx
=> Now you can see 4 columns in Resources

frontend/package-lock.json, frontend/package.json, frontend/src/components/NavBar.jsx, frontend/src/redux/actions/userAction.js, frontend/src/redux/reducers/userReducer.js, frontend/src/redux/store.js
So there is something i want to discuss @BisiOlaYemi @vwakesahu i added logout functionality, and removing the JWT from local storage but the cache is not getting refreshed. hence i am realoading the page after logout. It probably counted as a bad user experience. Does anyone one of you know wny better method?
=> Logout Functionality Added

frontend/src/components/Footer.jsx
Increased top margin of Footer component to remove the gap between components.
=> Bug: Fixed the margin of Footer component

frontend/src/components/NavBar.jsx
closes #74 
Used NavLink from react-router-dom to check for active state, also changed the underline to make it more adaptable to the active state.
=> Updated highlight isssue on nav links

backend/controllers/authController.js, frontend/src/App.jsx, frontend/src/components/NavBar.jsx, frontend/src/pages/user/UserDashBoard.jsx, frontend/src/pages/user/UserInfo.jsx, frontend/src/pages/user/UserJobHistory.jsx, frontend/src/redux/actions/userAction.js, frontend/src/redux/reducers/userReducer.js, frontend/src/redux/store.js
Feature 1: 
You can see User DashBoard, where he can see his applied jobs
Feature 2: 
The user will get navigate to user dashboard and admin will navigate to admin dashboard.
So many small and big changes in frotnend.
=> Front end changes

frontend/src/App.jsx, frontend/src/components/AdminRoute.jsx, frontend/src/components/NavBar.jsx, frontend/src/pages/Login.jsx, frontend/src/pages/admin/AdminCategory.jsx, frontend/src/pages/admin/AdminDashboard.jsx, frontend/src/pages/admin/AdminJobs.jsx, frontend/src/pages/admin/AdminUsers.jsx
Added a protectected Route for Admin + Admin category + admin Users +  admin jobs
=> All Admin Routes are Configured

frontend/src/components/ContactUs.jsx, frontend/src/components/Testimonials.jsx
Changes I made : 
1)
h-screen (removed) -->reduced gap in between 2 sections (the gap occured at screen-size >=768px)
from Testimonials.jsx
Before : 
<section className="grid grid-cols-1 md:grid-cols-2 gap-2 w-full sm:m-12 h-screen" id="home" >
After : 
<section className="grid grid-cols-1 md:grid-cols-2 gap-2 w-full sm:m-12" id="home" >
2)
wrote 'Contact Us' in place of 'Contact Sales' in ContactUs.jsx
Before : 
<h2 className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Contact sales</h2>
After : 
<h2 className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Contact Us</h2>
3)
Removed 'py-32' and wrote 'pt-4 and pb-32' in ContactUs.jsx for reducing the gap below the 3d girl image and kept the lower padding same
Before : 
<div className="isolate bg-white …
=> changed ContactUs.jsx and Testimonials.jsx

backend/apiHelp.js, frontend/package.json, frontend/src/components/NavBar.jsx, frontend/src/pages/global/Sidebar.jsx, frontend/src/redux/actions/userAction.js
So the logout wasnt working cause the the logout  function wasnt waiting for userLogoutAction() to get completed. 
hence whenever you are performing the logout or want to use the userLogOutAction use async await over there.
=> The Logout issue Fixed

frontend/package-lock.json, frontend/package.json, frontend/src/components/NavBar.jsx, frontend/src/components/StatComponent.jsx, frontend/src/pages/global/HeaderTop.jsx, frontend/src/pages/global/Layout.jsx, frontend/src/pages/global/Sidebar.jsx, frontend/src/pages/user/UserDashBoard.jsx, frontend/src/pages/user/UserInfoDashboard.jsx, frontend/src/pages/user/UserJobHistory.jsx
=> Optimized Navbar Performance By removing extra functions

frontend/src/components/FindJobsGlimpse.jsx, frontend/src/components/SearchInput.jsx, frontend/src/pages/FindJob.jsx, frontend/src/pages/Login.jsx, frontend/src/pages/SignUp.jsx
=> linked FindJob of HomePage
